#ifndef KEYCODE_WINDOWS_H
#define KEYCODE_WINDOWS_H

#include <windows.h>
#include <WinUser.h>

// TODO: Transcripe to use WinUser.h macros rather than copying the constants
enum KeyCode {
    K_UNKNOWN             = 0x0, // *DEFAULT* (flag used in auto file gen to signal default/unknown keycode)
    K_BackSpace           = 0x08,
    K_Tab                 = VK_TAB,
    K_Return              = 0x0D,
    K_Shift               = 0x10,
    K_LShift              = 0xA0,
    K_RShift              = 0xA1,
    K_Control             = 0x11,
    K_ControlLeft         = 162,
    K_ControlRight        = 163,
    K_Menu                = VK_MENU,
    K_LMenu               = VK_LMENU,
    K_RMenu               = VK_RMENU,
    K_Capital             = VK_CAPITAL,
    K_Escape              = 0x1B,
    K_Space               = 0x20,
    K_PageUp              = 0x21,
    K_PageDown            = 0x22,
    K_End                 = 0x23,
    K_Home                = 0x24,
    K_Left                = 0x25,
    K_Up                  = 0x26,
    K_Right               = 0x27,
    K_Down                = 0x28,
    K_Select              = 0x29,
    K_Print               = 0x2A,
    K_Execute             = 0x2B,
    K_Snapshot            = 0x2C,
    K_Insert              = 0x2D,
    K_Delete              = 0x2E,
    K_Help                = 0x2F,
    K_0                   = '0',
    K_1                   = '1',
    K_2                   = '2',
    K_3                   = '3',
    K_4                   = '4',
    K_5                   = '5',
    K_6                   = '6',
    K_7                   = '7',
    K_8                   = '8',
    K_9                   = '9',
    K_A                   = 'A',
    K_B                   = 'B',
    K_C                   = 'C',
    K_D                   = 'D',
    K_E                   = 'E',
    K_F                   = 'F',
    K_G                   = 'G',
    K_H                   = 'H',
    K_I                   = 'I',
    K_J                   = 'J',
    K_K                   = 'K',
    K_L                   = 'L',
    K_M                   = 'M',
    K_N                   = 'N',
    K_O                   = 'O',
    K_P                   = 'P',
    K_Q                   = 'Q',
    K_R                   = 'R',
    K_S                   = 'S',
    K_T                   = 'T',
    K_U                   = 'U',
    K_V                   = 'V',
    K_W                   = 'W',
    K_X                   = 'X',
    K_Y                   = 'Y',
    K_Z                   = 'Z',
    K_LeftWindows         = 0x5B,
    K_RightWindows        = 0x5C,
    K_Apps                = 0x5D,
    K_Sleep               = 0x5F,
    K_Numpad0             = 0x60,
    K_Numpad1             = 0x61,
    K_Numpad2             = 0x62,
    K_Numpad3             = 0x63,
    K_Numpad4             = 0x64,
    K_Numpad5             = 0x65,
    K_Numpad6             = 0x66,
    K_Numpad7             = 0x67,
    K_Numpad8             = 0x68,
    K_Numpad9             = 0x69,
    K_Multiply            = 0x6A,
    K_Add                 = 0x6B,
    K_Subtract            = 0x6D,
    K_Decimal             = 0x6E,
    K_Divide              = 0x6F,
    K_F1                  = 0x70,
    K_F2                  = 0x71,
    K_F3                  = 0x72,
    K_F4                  = 0x73,
    K_F5                  = 0x74,
    K_F6                  = 0x75,
    K_F7                  = 0x76,
    K_F8                  = 0x77,
    K_F9                  = 0x78,
    K_F10                 = 0x79,
    K_F11                 = 0x7A,
    K_F12                 = 0x7B,
    K_F13                 = 0x7C,
    K_F14                 = 0x7D,
    K_F15                 = 0x7E,
    K_F16                 = 0x7F,
    K_F17                 = 0x80,
    K_F18                 = 0x81,
    K_F19                 = 0x82,
    K_F20                 = 0x83,
    K_F21                 = 0x84,
    K_F22                 = 0x85,
    K_F23                 = 0x86,
    K_F24                 = 0x87,
    K_Numlock             = 0x90,
    K_Scroll              = 0x91,
    K_Equal               = 0x92,   // '=' key on numpad
    K_Colon_Semicolon     = 0xBA,   // ';:' for US
    K_Plus_Equal          = 0xBB,   // '+' any country
    K_Comma_LAngleBracket             = 0xBC,   // ',' any country
    K_Minus_Underscore                = 0xBD,   // '-' any country
    K_Period_RAngleBracket            = 0xBE,   // '.' any country
    K_ForwardSlash_QuestionMark       = 0xBF,   // '/?' for US
    K_Grave_Tilde                     = 0xC0,   // '`~' for US
    K_LSquareBracket_LCurlyBracket    = 0xDB,  //  '[{' for US
    K_Backslash_Pipe                  = 0xDC,  //  '\|' for US
    K_RSquareBracket_RCurlyBracket    = 0xDD,  //  ']}' for US
    K_SingleQuote_DoubleQuote         = 0xDE,  //  ''"' for US
};

#endif // KEYCODE_WINDOWS_H

