
# This script takes in a c file identifies an enum
# It then reads in the enum and constructs a nested switch statement recreating the trie

# Goals:
#   trie should be represented in code rather than needing to alloc object
#   minamize nested switch statements, use strcmp if large stretch without more than one branch
#   handles invalid strings, can't assume each input string is in trie
#   generated code is human readable


ENUM_FILE = "include/linux/keycode_linux.h"
OUTPUT_FILE = "src/keycode_from_str.c"

# Any needed boiler plate to add at start of file
FILE_PREFIX = """
#include <keycode.h>
#include <string.h>

/**
  * This file is autogenerated by scripts/create_comp_time_trie.py
  * It uses the include/linux/keycode_linux.h to find the 
  * keycode eums. Only the identifier names are used not the values
  * It is expected for the names to remain consistant between the
  * the different enums for each platform
  */
  
"""

FUNCTION_NAME = "keycodeFromString" # Name of generated function
ARGUMENT_NAME = "keyName" # name used for string parameter of generated function
VALUES_SKIP_PREFIX = "K_" # expected prefix for each value in the enum, skipped in the string compare
VALUES_PREFIX = "" # expected prefix for each value in the enum, included in the string compare


FUNCTION_DESCRIPTION = """
/** Convert a string into a keycode. The string name
  * of a keycode is based on the keycode enum without the "K_" prefix
  * If the given string is not recognized it returns K_UNKNOWN 
  */
"""



class Node:

    def __init__(self, idx, strings):
        self.idx = idx
        self.terminals = []
        self.bins = []
        self.splits = [] #chars determining splits

        # Split the strings into different bins by the value at idx
        for str in strings:
            if len(str) == self.idx:
                self.terminals.append(str)
            else:
                try:
                    bin_idx = self.splits.index(str[idx])
                    self.bins[bin_idx].append(str)
                except:
                    self.bins.append([str])
                    self.splits.append(str[idx])

        if len(self.terminals) > 1:
            print(f"WARNING: Multiple identical strings encountered {self.terminals}")
        
        self.children = []
        for split_idx in range(len(self.splits)):
            node = Node(self.idx + 1, self.bins[split_idx])
            self.children.append(node)

            
def print_trie(trie: Node, cur_depth=0):
    print("  "*cur_depth, end="")
    print(f"switch str at {trie.idx}")
    for bin_idx in range(len(trie.bins)):
        print("  "*cur_depth, end="")
        print("char", trie.splits[bin_idx])
        print_trie(trie.children[bin_idx], cur_depth+1)
    if len(trie.terminals) > 0:
        print("  "*cur_depth + "default", trie.terminals)

def write_strcmp_terminal(trie: Node, file, default: str, cur_depth: int):
    file.write("  "*cur_depth)
    # file.write("Strcmp here\n")
    full_str = trie.bins[0][0]
    cut_str = full_str[trie.idx:]
    file.write(f"if (!strcmp(&{ARGUMENT_NAME}[{trie.idx}], \"{cut_str}\")) {'{'}\n")
    file.write("  "*(cur_depth+1) + f"return {VALUES_SKIP_PREFIX}{full_str};\n")
    file.write("  "*cur_depth + "} else {\n")
    file.write("  "*(cur_depth+1) + "return "+default+";\n")
    file.write("  "*cur_depth + "}\n")
    pass

def write_if_else_terminal(trie: Node, file, default: str, cur_depth: int):
    file.write("  "*cur_depth)
    # file.write("Strcmp here\n")
    full_str = trie.terminals[0]
    file.write(f"if ({ARGUMENT_NAME}[{trie.idx}] == '\\0') return {VALUES_SKIP_PREFIX}{full_str};\n")
    file.write("  "*cur_depth + "else return "+default+";\n")

def write_trie_to_C_worker(trie: Node, file, default: str, cur_depth: int):
    # If only 1 string left in branch, and isn't temrinal,
    # handle with strcmp
    if len(trie.bins) == 1 and len(trie.terminals) == 0 and len(trie.bins[0]) == 1:
        write_strcmp_terminal(trie, file, default, cur_depth)
        return
    
    # If only 1 string left and is terminal,
    # handle with if else statement
    if len(trie.bins) == 0 and len(trie.terminals) == 1:
        write_if_else_terminal(trie, file, default, cur_depth)
        return

    file.write("  "*cur_depth)
    file.write(f"switch ({ARGUMENT_NAME}[{trie.idx}]) " + "{\n")
    for bin_idx in range(len(trie.bins)):
        file.write("  "*cur_depth)
        file.write(f"case '{trie.splits[bin_idx]}':\n")
        write_trie_to_C_worker(trie.children[bin_idx], file, default, cur_depth+1)
    if len(trie.terminals) > 0:
        file.write("  "*cur_depth + "case '\\0': return " + VALUES_SKIP_PREFIX + trie.terminals[0] + ';\n')
    file.write("  "*cur_depth + "default: return " + default + ';\n')
    
    file.write("  "*cur_depth)
    file.write("}\n")

def write_trie_to_C(trie: Node, enum_name: str, default: str, file):

    file.write(FILE_PREFIX)

    # Write function header
    file.write(FUNCTION_DESCRIPTION)
    file.write(f"enum {enum_name} {FUNCTION_NAME}(const char *{ARGUMENT_NAME}) {'{'}\n")

    if VALUES_PREFIX != "":
        file.write(f"if ({ARGUMENT_NAME}[0] != '{VALUES_PREFIX[0]}'")
        if len(trie.bins) != 1:
            print("Fail")
            raise Exception("Encountered strings that conflict with specified prefix")
        trie = trie.children[0]
        for idx in range(1, len(VALUES_PREFIX)):
            if len(trie.bins) != 1:
                print("Fail")
                raise Exception("Encountered strings that conflict with specified prefix")
            trie = trie.children[0]
            file.write(f" || {ARGUMENT_NAME}[{idx}] != '{VALUES_PREFIX[idx]}'")
        file.write(") {\n  return NULL;\n}\n")
        
        
    write_trie_to_C_worker(trie, file, default, 1)

    file.write("}\n")



class EnumInfo:
    def read_enum_token(self, file) -> bool:
        line = file.readline()
        if not line:
            raise Exception("Encountered unexpecred end of line reading enum", self.enum_name)
        line = line.strip()
        if not line:
            return True
        if line[0] == '}':
            return False
        self.tokens.append(line.split(' ')[0])
        if "*DEFAULT*" in line:
            self.default = self.tokens[-1]
        
        print(f"Found token '{self.tokens[-1]}'")

        return True

    def read_enum(self, line: str, file):
        tokens = line.split(' ')
        self.enum_name = tokens[1].strip()
        print("Found enum", self.enum_name)
        while self.read_enum_token(file):
            pass
        
        return

    def __init__(self, path):
        self.enum_name: str = ""
        self.tokens: list[str] = []
        self.default: str = ""
        with open(path, 'r') as file:
            line = file.readline()
            while line:
                if line[0:len("enum")] == "enum":
                    return self.read_enum(line, file)
                line = file.readline()

    def cut_commented(self):
        self.tokens = list(filter(lambda a: a != '//', self.tokens))

    def cut_prefix(self, prefix: str):
        for i in range(0, len(self.tokens)):
            if prefix != self.tokens[i][0:len(prefix)]:
                raise Exception(f"Error: Encountered string '{self.tokens[i]}' without prefix '{prefix}'")
            self.tokens[i] = self.tokens[i][len(prefix):]

    
enum = EnumInfo(ENUM_FILE)
enum.cut_commented()
enum.cut_prefix(VALUES_SKIP_PREFIX)
trie = Node(0, enum.tokens)

# print_trie(trie)

with open(OUTPUT_FILE, 'w') as f:
    write_trie_to_C(trie, enum.enum_name, enum.default, f)

print("Finished")
