
#include <keycode.h>
#include <string.h>

/**
  * This file is autogenerated by scripts/create_comp_time_trie.py
  * It uses the include/windows/keycode_windows.h to find the 
  * keycode eums. Only the identifier names are used not the values
  * It is expected for the names to remain consistant between the
  * the different enums for each platform
  */
  

/** Convert a string into a keycode. The string name
  * of a keycode is based on the keycode enum without the "K_" prefix
  * If the given string is not recognized it returns K_UNKNOWN 
  */
enum KeyCode keycodeFromString(const char *keyName) {
  switch (keyName[0]) {
  case 'U':
    switch (keyName[1]) {
    case 'N':
      if (!strcmp(&keyName[2], "KNOWN")) {
        return K_UNKNOWN;
      } else {
        return K_UNKNOWN;
      }
    case 'p':
      if (keyName[2] == '\0') return K_Up;
      else return K_UNKNOWN;
    case '\0': return K_U;
    default: return K_UNKNOWN;
    }
  case 'B':
    switch (keyName[1]) {
    case 'a':
      switch (keyName[2]) {
      case 'c':
        switch (keyName[3]) {
        case 'k':
          switch (keyName[4]) {
          case 'S':
            if (!strcmp(&keyName[5], "pace")) {
              return K_BackSpace;
            } else {
              return K_UNKNOWN;
            }
          case 's':
            if (!strcmp(&keyName[5], "lash_Pipe")) {
              return K_Backslash_Pipe;
            } else {
              return K_UNKNOWN;
            }
          default: return K_UNKNOWN;
          }
        default: return K_UNKNOWN;
        }
      default: return K_UNKNOWN;
      }
    case '\0': return K_B;
    default: return K_UNKNOWN;
    }
  case 'T':
    switch (keyName[1]) {
    case 'a':
      if (!strcmp(&keyName[2], "b")) {
        return K_Tab;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_T;
    default: return K_UNKNOWN;
    }
  case 'R':
    switch (keyName[1]) {
    case 'e':
      if (!strcmp(&keyName[2], "turn")) {
        return K_Return;
      } else {
        return K_UNKNOWN;
      }
    case 'S':
      switch (keyName[2]) {
      case 'h':
        if (!strcmp(&keyName[3], "ift")) {
          return K_RShift;
        } else {
          return K_UNKNOWN;
        }
      case 'q':
        if (!strcmp(&keyName[3], "uareBracket_RCurlyBracket")) {
          return K_RSquareBracket_RCurlyBracket;
        } else {
          return K_UNKNOWN;
        }
      default: return K_UNKNOWN;
      }
    case 'M':
      if (!strcmp(&keyName[2], "enu")) {
        return K_RMenu;
      } else {
        return K_UNKNOWN;
      }
    case 'i':
      switch (keyName[2]) {
      case 'g':
        switch (keyName[3]) {
        case 'h':
          switch (keyName[4]) {
          case 't':
            switch (keyName[5]) {
            case 'W':
              if (!strcmp(&keyName[6], "indows")) {
                return K_RightWindows;
              } else {
                return K_UNKNOWN;
              }
            case '\0': return K_Right;
            default: return K_UNKNOWN;
            }
          default: return K_UNKNOWN;
          }
        default: return K_UNKNOWN;
        }
      default: return K_UNKNOWN;
      }
    case '\0': return K_R;
    default: return K_UNKNOWN;
    }
  case 'S':
    switch (keyName[1]) {
    case 'h':
      if (!strcmp(&keyName[2], "ift")) {
        return K_Shift;
      } else {
        return K_UNKNOWN;
      }
    case 'p':
      if (!strcmp(&keyName[2], "ace")) {
        return K_Space;
      } else {
        return K_UNKNOWN;
      }
    case 'e':
      if (!strcmp(&keyName[2], "lect")) {
        return K_Select;
      } else {
        return K_UNKNOWN;
      }
    case 'n':
      if (!strcmp(&keyName[2], "apshot")) {
        return K_Snapshot;
      } else {
        return K_UNKNOWN;
      }
    case 'l':
      if (!strcmp(&keyName[2], "eep")) {
        return K_Sleep;
      } else {
        return K_UNKNOWN;
      }
    case 'u':
      if (!strcmp(&keyName[2], "btract")) {
        return K_Subtract;
      } else {
        return K_UNKNOWN;
      }
    case 'c':
      if (!strcmp(&keyName[2], "roll")) {
        return K_Scroll;
      } else {
        return K_UNKNOWN;
      }
    case 'i':
      if (!strcmp(&keyName[2], "ngleQuote_DoubleQuote")) {
        return K_SingleQuote_DoubleQuote;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_S;
    default: return K_UNKNOWN;
    }
  case 'L':
    switch (keyName[1]) {
    case 'S':
      switch (keyName[2]) {
      case 'h':
        if (!strcmp(&keyName[3], "ift")) {
          return K_LShift;
        } else {
          return K_UNKNOWN;
        }
      case 'q':
        if (!strcmp(&keyName[3], "uareBracket_LCurlyBracket")) {
          return K_LSquareBracket_LCurlyBracket;
        } else {
          return K_UNKNOWN;
        }
      default: return K_UNKNOWN;
      }
    case 'M':
      if (!strcmp(&keyName[2], "enu")) {
        return K_LMenu;
      } else {
        return K_UNKNOWN;
      }
    case 'e':
      switch (keyName[2]) {
      case 'f':
        switch (keyName[3]) {
        case 't':
          switch (keyName[4]) {
          case 'W':
            if (!strcmp(&keyName[5], "indows")) {
              return K_LeftWindows;
            } else {
              return K_UNKNOWN;
            }
          case '\0': return K_Left;
          default: return K_UNKNOWN;
          }
        default: return K_UNKNOWN;
        }
      default: return K_UNKNOWN;
      }
    case '\0': return K_L;
    default: return K_UNKNOWN;
    }
  case 'C':
    switch (keyName[1]) {
    case 'o':
      switch (keyName[2]) {
      case 'n':
        switch (keyName[3]) {
        case 't':
          switch (keyName[4]) {
          case 'r':
            switch (keyName[5]) {
            case 'o':
              switch (keyName[6]) {
              case 'l':
                switch (keyName[7]) {
                case 'L':
                  if (!strcmp(&keyName[8], "eft")) {
                    return K_ControlLeft;
                  } else {
                    return K_UNKNOWN;
                  }
                case 'R':
                  if (!strcmp(&keyName[8], "ight")) {
                    return K_ControlRight;
                  } else {
                    return K_UNKNOWN;
                  }
                case '\0': return K_Control;
                default: return K_UNKNOWN;
                }
              default: return K_UNKNOWN;
              }
            default: return K_UNKNOWN;
            }
          default: return K_UNKNOWN;
          }
        default: return K_UNKNOWN;
        }
      case 'l':
        if (!strcmp(&keyName[3], "on_Semicolon")) {
          return K_Colon_Semicolon;
        } else {
          return K_UNKNOWN;
        }
      case 'm':
        if (!strcmp(&keyName[3], "ma_LAngleBracket")) {
          return K_Comma_LAngleBracket;
        } else {
          return K_UNKNOWN;
        }
      default: return K_UNKNOWN;
      }
    case 'a':
      if (!strcmp(&keyName[2], "pital")) {
        return K_Capital;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_C;
    default: return K_UNKNOWN;
    }
  case 'M':
    switch (keyName[1]) {
    case 'e':
      if (!strcmp(&keyName[2], "nu")) {
        return K_Menu;
      } else {
        return K_UNKNOWN;
      }
    case 'u':
      if (!strcmp(&keyName[2], "ltiply")) {
        return K_Multiply;
      } else {
        return K_UNKNOWN;
      }
    case 'i':
      if (!strcmp(&keyName[2], "nus_Underscore")) {
        return K_Minus_Underscore;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_M;
    default: return K_UNKNOWN;
    }
  case 'E':
    switch (keyName[1]) {
    case 's':
      if (!strcmp(&keyName[2], "cape")) {
        return K_Escape;
      } else {
        return K_UNKNOWN;
      }
    case 'n':
      if (!strcmp(&keyName[2], "d")) {
        return K_End;
      } else {
        return K_UNKNOWN;
      }
    case 'x':
      if (!strcmp(&keyName[2], "ecute")) {
        return K_Execute;
      } else {
        return K_UNKNOWN;
      }
    case 'q':
      if (!strcmp(&keyName[2], "ual")) {
        return K_Equal;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_E;
    default: return K_UNKNOWN;
    }
  case 'P':
    switch (keyName[1]) {
    case 'a':
      switch (keyName[2]) {
      case 'g':
        switch (keyName[3]) {
        case 'e':
          switch (keyName[4]) {
          case 'U':
            if (!strcmp(&keyName[5], "p")) {
              return K_PageUp;
            } else {
              return K_UNKNOWN;
            }
          case 'D':
            if (!strcmp(&keyName[5], "own")) {
              return K_PageDown;
            } else {
              return K_UNKNOWN;
            }
          default: return K_UNKNOWN;
          }
        default: return K_UNKNOWN;
        }
      default: return K_UNKNOWN;
      }
    case 'r':
      if (!strcmp(&keyName[2], "int")) {
        return K_Print;
      } else {
        return K_UNKNOWN;
      }
    case 'l':
      if (!strcmp(&keyName[2], "us_Equal")) {
        return K_Plus_Equal;
      } else {
        return K_UNKNOWN;
      }
    case 'e':
      if (!strcmp(&keyName[2], "riod_RAngleBracket")) {
        return K_Period_RAngleBracket;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_P;
    default: return K_UNKNOWN;
    }
  case 'H':
    switch (keyName[1]) {
    case 'o':
      if (!strcmp(&keyName[2], "me")) {
        return K_Home;
      } else {
        return K_UNKNOWN;
      }
    case 'e':
      if (!strcmp(&keyName[2], "lp")) {
        return K_Help;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_H;
    default: return K_UNKNOWN;
    }
  case 'D':
    switch (keyName[1]) {
    case 'o':
      if (!strcmp(&keyName[2], "wn")) {
        return K_Down;
      } else {
        return K_UNKNOWN;
      }
    case 'e':
      switch (keyName[2]) {
      case 'l':
        if (!strcmp(&keyName[3], "ete")) {
          return K_Delete;
        } else {
          return K_UNKNOWN;
        }
      case 'c':
        if (!strcmp(&keyName[3], "imal")) {
          return K_Decimal;
        } else {
          return K_UNKNOWN;
        }
      default: return K_UNKNOWN;
      }
    case 'i':
      if (!strcmp(&keyName[2], "vide")) {
        return K_Divide;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_D;
    default: return K_UNKNOWN;
    }
  case 'I':
    switch (keyName[1]) {
    case 'n':
      if (!strcmp(&keyName[2], "sert")) {
        return K_Insert;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_I;
    default: return K_UNKNOWN;
    }
  case '0':
    if (keyName[1] == '\0') return K_0;
    else return K_UNKNOWN;
  case '1':
    if (keyName[1] == '\0') return K_1;
    else return K_UNKNOWN;
  case '2':
    if (keyName[1] == '\0') return K_2;
    else return K_UNKNOWN;
  case '3':
    if (keyName[1] == '\0') return K_3;
    else return K_UNKNOWN;
  case '4':
    if (keyName[1] == '\0') return K_4;
    else return K_UNKNOWN;
  case '5':
    if (keyName[1] == '\0') return K_5;
    else return K_UNKNOWN;
  case '6':
    if (keyName[1] == '\0') return K_6;
    else return K_UNKNOWN;
  case '7':
    if (keyName[1] == '\0') return K_7;
    else return K_UNKNOWN;
  case '8':
    if (keyName[1] == '\0') return K_8;
    else return K_UNKNOWN;
  case '9':
    if (keyName[1] == '\0') return K_9;
    else return K_UNKNOWN;
  case 'A':
    switch (keyName[1]) {
    case 'p':
      if (!strcmp(&keyName[2], "ps")) {
        return K_Apps;
      } else {
        return K_UNKNOWN;
      }
    case 'd':
      if (!strcmp(&keyName[2], "d")) {
        return K_Add;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_A;
    default: return K_UNKNOWN;
    }
  case 'F':
    switch (keyName[1]) {
    case '1':
      switch (keyName[2]) {
      case '0':
        if (keyName[3] == '\0') return K_F10;
        else return K_UNKNOWN;
      case '1':
        if (keyName[3] == '\0') return K_F11;
        else return K_UNKNOWN;
      case '2':
        if (keyName[3] == '\0') return K_F12;
        else return K_UNKNOWN;
      case '3':
        if (keyName[3] == '\0') return K_F13;
        else return K_UNKNOWN;
      case '4':
        if (keyName[3] == '\0') return K_F14;
        else return K_UNKNOWN;
      case '5':
        if (keyName[3] == '\0') return K_F15;
        else return K_UNKNOWN;
      case '6':
        if (keyName[3] == '\0') return K_F16;
        else return K_UNKNOWN;
      case '7':
        if (keyName[3] == '\0') return K_F17;
        else return K_UNKNOWN;
      case '8':
        if (keyName[3] == '\0') return K_F18;
        else return K_UNKNOWN;
      case '9':
        if (keyName[3] == '\0') return K_F19;
        else return K_UNKNOWN;
      case '\0': return K_F1;
      default: return K_UNKNOWN;
      }
    case '2':
      switch (keyName[2]) {
      case '0':
        if (keyName[3] == '\0') return K_F20;
        else return K_UNKNOWN;
      case '1':
        if (keyName[3] == '\0') return K_F21;
        else return K_UNKNOWN;
      case '2':
        if (keyName[3] == '\0') return K_F22;
        else return K_UNKNOWN;
      case '3':
        if (keyName[3] == '\0') return K_F23;
        else return K_UNKNOWN;
      case '4':
        if (keyName[3] == '\0') return K_F24;
        else return K_UNKNOWN;
      case '\0': return K_F2;
      default: return K_UNKNOWN;
      }
    case '3':
      if (keyName[2] == '\0') return K_F3;
      else return K_UNKNOWN;
    case '4':
      if (keyName[2] == '\0') return K_F4;
      else return K_UNKNOWN;
    case '5':
      if (keyName[2] == '\0') return K_F5;
      else return K_UNKNOWN;
    case '6':
      if (keyName[2] == '\0') return K_F6;
      else return K_UNKNOWN;
    case '7':
      if (keyName[2] == '\0') return K_F7;
      else return K_UNKNOWN;
    case '8':
      if (keyName[2] == '\0') return K_F8;
      else return K_UNKNOWN;
    case '9':
      if (keyName[2] == '\0') return K_F9;
      else return K_UNKNOWN;
    case 'o':
      if (!strcmp(&keyName[2], "rwardSlash_QuestionMark")) {
        return K_ForwardSlash_QuestionMark;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_F;
    default: return K_UNKNOWN;
    }
  case 'G':
    switch (keyName[1]) {
    case 'r':
      if (!strcmp(&keyName[2], "ave_Tilde")) {
        return K_Grave_Tilde;
      } else {
        return K_UNKNOWN;
      }
    case '\0': return K_G;
    default: return K_UNKNOWN;
    }
  case 'J':
    if (keyName[1] == '\0') return K_J;
    else return K_UNKNOWN;
  case 'K':
    if (keyName[1] == '\0') return K_K;
    else return K_UNKNOWN;
  case 'N':
    switch (keyName[1]) {
    case 'u':
      switch (keyName[2]) {
      case 'm':
        switch (keyName[3]) {
        case 'p':
          switch (keyName[4]) {
          case 'a':
            switch (keyName[5]) {
            case 'd':
              switch (keyName[6]) {
              case '0':
                if (keyName[7] == '\0') return K_Numpad0;
                else return K_UNKNOWN;
              case '1':
                if (keyName[7] == '\0') return K_Numpad1;
                else return K_UNKNOWN;
              case '2':
                if (keyName[7] == '\0') return K_Numpad2;
                else return K_UNKNOWN;
              case '3':
                if (keyName[7] == '\0') return K_Numpad3;
                else return K_UNKNOWN;
              case '4':
                if (keyName[7] == '\0') return K_Numpad4;
                else return K_UNKNOWN;
              case '5':
                if (keyName[7] == '\0') return K_Numpad5;
                else return K_UNKNOWN;
              case '6':
                if (keyName[7] == '\0') return K_Numpad6;
                else return K_UNKNOWN;
              case '7':
                if (keyName[7] == '\0') return K_Numpad7;
                else return K_UNKNOWN;
              case '8':
                if (keyName[7] == '\0') return K_Numpad8;
                else return K_UNKNOWN;
              case '9':
                if (keyName[7] == '\0') return K_Numpad9;
                else return K_UNKNOWN;
              default: return K_UNKNOWN;
              }
            default: return K_UNKNOWN;
            }
          default: return K_UNKNOWN;
          }
        case 'l':
          if (!strcmp(&keyName[4], "ock")) {
            return K_Numlock;
          } else {
            return K_UNKNOWN;
          }
        default: return K_UNKNOWN;
        }
      default: return K_UNKNOWN;
      }
    case '\0': return K_N;
    default: return K_UNKNOWN;
    }
  case 'O':
    if (keyName[1] == '\0') return K_O;
    else return K_UNKNOWN;
  case 'Q':
    if (keyName[1] == '\0') return K_Q;
    else return K_UNKNOWN;
  case 'V':
    if (keyName[1] == '\0') return K_V;
    else return K_UNKNOWN;
  case 'W':
    if (keyName[1] == '\0') return K_W;
    else return K_UNKNOWN;
  case 'X':
    if (keyName[1] == '\0') return K_X;
    else return K_UNKNOWN;
  case 'Y':
    if (keyName[1] == '\0') return K_Y;
    else return K_UNKNOWN;
  case 'Z':
    if (keyName[1] == '\0') return K_Z;
    else return K_UNKNOWN;
  default: return K_UNKNOWN;
  }
}
